# Generated by Django 6.0.3 on 2026-03-12 17:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("IN_PERSON", "In-Person"),
                            ("VIRTUAL", "Virtual"),
                            ("HYBRID", "Hybrid"),
                        ],
                        default="IN_PERSON",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("LIVE", "Live"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FUNDRAISER", "Fundraiser"),
                            ("WORKSHOP", "Workshop"),
                            ("MEETUP", "Meetup"),
                            ("VOLUNTEER", "Volunteer"),
                            ("SOCIAL", "Social"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("cover_image_url", models.URLField(blank=True)),
                ("is_private", models.BooleanField(default=False)),
                ("start_datetime", models.DateTimeField(blank=True, null=True)),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "timezone",
                    models.CharField(default="America/Los_Angeles", max_length=50),
                ),
                ("doors_open_time", models.DateTimeField(blank=True, null=True)),
                ("date_tbd", models.BooleanField(default=False)),
                ("virtual_link", models.URLField(blank=True)),
                ("virtual_platform", models.CharField(blank=True, max_length=50)),
                ("refund_policy", models.JSONField(blank=True, default=dict)),
                ("email_config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "db_table": "events",
                "unique_together": {("organization", "slug")},
            },
        ),
    ]
