# Generated by Django 6.0.3 on 2026-03-12 18:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventEmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("CONFIRMATION", "RSVP / Purchase Confirmation"),
                            ("REMINDER_48H", "48-Hour Reminder"),
                            ("REMINDER_DAY_OF", "Day-Of Reminder"),
                            ("EVENT_UPDATE", "Event Update"),
                            ("CANCELLATION", "Event Cancellation"),
                            ("POST_EVENT_THANKS", "Post-Event Thank You"),
                            ("NEW_REGISTRATION", "New Registration Alert"),
                            ("DAILY_SUMMARY", "Daily Summary"),
                            ("LOW_INVENTORY", "Low Inventory Alert"),
                            ("REFUND_PROCESSED", "Refund Processed"),
                            ("CUSTOM_BULK", "Custom Bulk Email"),
                        ],
                        max_length=30,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("BOUNCED", "Bounced"),
                        ],
                        default="SENT",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="events.event",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "event_email_logs",
                "ordering": ["-sent_at"],
            },
        ),
    ]
