# Generated by Django 6.0.3 on 2026-03-12 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketTier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("quantity_total", models.PositiveIntegerField()),
                ("quantity_sold", models.PositiveIntegerField(default=0)),
                ("sales_start", models.DateTimeField(blank=True, null=True)),
                ("sales_end", models.DateTimeField(blank=True, null=True)),
                ("min_per_order", models.PositiveIntegerField(default=1)),
                ("max_per_order", models.PositiveIntegerField(default=10)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("HIDDEN", "Hidden"),
                            ("INVITE_ONLY", "Invite Only"),
                        ],
                        default="PUBLIC",
                        max_length=20,
                    ),
                ),
                (
                    "attendance_mode",
                    models.CharField(
                        choices=[("IN_PERSON", "In-Person"), ("VIRTUAL", "Virtual")],
                        default="IN_PERSON",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_tiers",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "db_table": "ticket_tiers",
                "ordering": ["sort_order", "price"],
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("FIXED", "Fixed Amount"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("applicable_tier_ids", models.JSONField(blank=True, default=list)),
                ("usage_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("per_customer_limit", models.PositiveIntegerField(default=1)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_codes",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "db_table": "promo_codes",
                "unique_together": {("event", "code")},
            },
        ),
    ]
