# Generated by Django 6.0.3 on 2026-03-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="code",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
